- name: Nginx
  hosts: all
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: Restart Nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
