- name: Demo on variables
  hosts: localhost
  connection: local
  variables:
    URL: news.google.com
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        URL: News website is {{ URL }}