- name: Variable
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
    - name: Declare Task level variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.google.com