- name: Demo on variables
  hosts: localhost
  connection: local
  become: true
  vars:
    URL: google.com
  tasks:
    - name: Demo on variables
      ansible.builtin.debug:
        msg: URL = {{ URL }}
