- name: Demo on conditions
  hosts: localhost
  connection: local
  become: true
  vars:
    Fruit: true
    Vegetable: true
  tasks:
    - name: Demo on fruits
      ansible.builtin.debug:
        msg: Fruit Name - carrot
      when: Fruit is true
    - name: Demo on vegetable
      ansible.builtin.debug:
        msg: Vegetable Name - Tomato
      when: Vegetable is true