- name: Variable Types
  hosts: localhost
  connection: local
  vars:
    fruit_name: Orange # string
    quantity: 100 # number
    for_sale: 'true' # boolean, Booleans supported by ansible are yes/no true/false , Boolean becomes string if you quote it.
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: Fruit Name - {{ fruit_name }}, Quantity - {{ quantity }}
      when: for_sale