- name: Demo on vars type
  hosts: localhost
  connection: local
  become: true
  vars:
    Fruit_Name: "apple"
    Quantity: 100
    for_sale: 'true'
  tasks:
    - name: Print Business Message
      ansible.builtin.debug:
        msg: "Fruit Name - {{ Fruit_Name }}, Quantity - {{ Quantity }}"