- name: Demo on loops
  hosts: localhost
  connection: local
  vars:
    fruits:
      - apple
      - pineapple
      - Gauva
      - Orange
      - Sweet potato
  tasks:
    - name: Print Fruit Names
      ansible.builtin.debug:
        msg: Fruit Name is {{ item }}
      loop: "{{ fruits }}"

