- name: Demo on loops
  hosts: localhost
  connection: local
  vars:
    fruits:
      - apple
      - pineapple
      - Gauva
      - Orange
      - Sweet potato
  tasks:
    - name: Print Fruit Name - 1
      ansible.builtin.debug:
        msg: Fruit Name is {{ item }}
      loop: "{{ fruits }}"
    - name: Print Fruit Name - 2
      ansible.builtin.debug:
        msg: Fruit Name is {{ item }}
      loop:
        - tomato
        - potato
        - mouse
    - name: Print Fruit Name - 3
      ansible.builtin.debug:
        msg: Fruit Name is {{ item.Fruit_Name }}, Quantity is {{ item.Quantity }}
      loop:
        - { Fruit_Name: "apple", Quantity: 100 }
        - { Fruit_Name: "tomato", Quantity: 500 }

