
- name: Demo on loops
  hosts: localhost
  connection: local
  vars:
    fruits:
      - banana
      - apple
      - potato
      - pineapple
  tasks:
    - name: Print Fruit Names
      ansible.builtin.debug:
        msg: "Fruit name is {{ item }}"
      loop: "{{ fruits }}"

    - name: Print Fruit Names - Examples
      ansible.builtin.debug:
        msg: "Fruit message is {{ item }}"
      loop:
        - potato
        - pineapple
        - tomato
    - name: Print Fruit details
      ansible.builtin.debug:
        msg: "Fruit name is {{ item.Fruit_name }}, Quantity is {{ item.quantity }}"
      loop:
        - { Fruit_name: "apple", quantity: 100}
        - { Fruit_name: "orange", quantity: 150 }


