- name: Demo on template
  hosts: localhost
  connection: local
  vars:
    fruit_name:
      - apple
  tasks:
    - name: Print Template
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt
