- name: Demo on ansible template
  hosts: all
  connection: local
  vars:
    car_name: Nexa
  tasks:
    - name: Print Message
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt

# Im commiting the code


