- name: Demo on Laptops
  hosts: all
  become: true
  vars:
    laptop_name:
      - hp
      - lenovo
      - samsung
  tasks:
    - name: Print Laptop service name
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt

