- name: Template Demo
  hosts: localhost
  connection: local
  vars:
    fruit_name: apple, pineapple, potato, tomato
  tasks:
    - ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt