- name: Demo on template
  hosts: localhost
  connection: local
  vars:
    name:
      - Akhilesh
  tasks:
    - name: Print My name
      ansible.builtin.template:
        src: test.txt
        dest: sample.txt